version: '3.6'
services:
  iris:
    image: intersystemsdc/iris-community:2021.1.0.215.3-zpm
    restart: always
    ports: 
      - 52774:52773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
